name: 'ptt_sentiment'
version: '1.0.0'
config-version: 2

profile: 'ptt_sentiment'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ptt_sentiment:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

vars:
  use_v2_pipeline: false

