import re
import time
import requests
from bs4 import BeautifulSoup
from datetime import datetime
from config import SKIP_KEYWORDS, PTT_SOURCE_NAME, PTT_SOURCE_URL, ARTICLES_TABLE, COMMENTS_TABLE, SOURCES_TABLE
from pg_helper import get_pg


def get_previous_page(soup):
    for item in soup:
        prev_soup = item.find("a", string=lambda t: t and "上頁" in t)
        if not prev_soup:
            continue
        prev_page = prev_soup.get("href")
        return prev_page
    return False


def _is_duplicate(cursor, article_url):
    # using %s to bypass the sql injection
    cursor.execute(f"SELECT article_id FROM {ARTICLES_TABLE} WHERE url = %s", (article_url,))
    return cursor.fetchone() is not None


def _get_or_create_source(cursor, source_name, source_url):#return the source_id
    cursor.execute(f"SELECT source_id FROM {SOURCES_TABLE} WHERE url = %s", (source_url,))
    row = cursor.fetchone()
    if row:
        return row[0]
    #id is auto-increment and generated by the databas
    cursor.execute(
        f"INSERT INTO {SOURCES_TABLE} (source_name, url) VALUES (%s, %s) RETURNING source_id",
        (source_name, source_url)
    )
    return cursor.fetchone()[0]


def _parse_push_count(text):
    """推文數文字轉整數：爆→100, XX→-100, X30→-30"""
    text = text.strip()
    if text == "爆":
        return 100
    if text.upper().startswith("X"):
        try:
            return -int(text[1:])
        except ValueError:
            return -100
    try:
        return int(text)
    except ValueError:
        return 0


def _extract_published_at(url):
    """從 PTT 文章 URL 提取發文時間"""
    match = re.search(r'M\.(\d+)\.', url)
    if match:
        return datetime.fromtimestamp(int(match.group(1)))#group(1) is first () content
    return None


def _insert_article(cursor, source_id, article_table):
    cursor.execute(f"""
        INSERT INTO {ARTICLES_TABLE} (source_id, title, push_count, author, url, content, published_at, scraped_at)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        RETURNING article_id""",
        (source_id, article_table["title"], article_table["push_count"],
         article_table["author"], article_table["url"], article_table["content"],
         article_table["published_at"], article_table["scraped_at"]))
    return cursor.fetchone()[0]


def _insert_comments(cursor, article_id, comments):
    for comment in comments:
        cursor.execute(f"""
            INSERT INTO {COMMENTS_TABLE} (article_id, user_id, push_tag, message)
            VALUES (%s, %s, %s, %s)""",
            (article_id, comment["User_id"], comment["Push_tag"], comment["Message"]))


def scrape_web_page_title(headers, url):
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "html.parser")
    data = soup.find_all("div", class_="r-ent")
    if not data:
        return False
    with get_pg() as conn:
        with conn.cursor() as cursor:
            source_id = _get_or_create_source(cursor, PTT_SOURCE_NAME, PTT_SOURCE_URL)
            for item in data:
                comment = item.find("div", class_="nrec")
                title   = item.find("div", class_="title")
                author  = item.find("div", class_="author")
                a_tag   = title.find("a")
                if not a_tag:
                    continue
                article_url = "https://www.ptt.cc" + a_tag.get("href")
                if any(keyword in title.text for keyword in SKIP_KEYWORDS):
                    continue
                if _is_duplicate(cursor, article_url):
                    continue
                web_page_content = scrape_web_page_content(headers, article_url)
                if not web_page_content:
                    continue
                push_txt = comment.text.strip() if comment and comment.text.strip() else "0"
                article_data = {
                    "title":        title.text.strip(),
                    "push_count":   _parse_push_count(push_txt),
                    "author":       author.text.strip(),
                    "url":          article_url,
                    "content":      web_page_content["Content"],
                    "published_at": _extract_published_at(article_url),
                    "scraped_at":   datetime.now(),
                }
                article_id = _insert_article(cursor, source_id, article_data)
                _insert_comments(cursor, article_id, web_page_content["Comment_info"])
    return True


def scrape_web_page_content(headers, url):
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "html.parser")
    main_content = soup.find("div", id="main-content")
    article_content = []
    comment_info    = []
    if main_content:
        for item in main_content.find_all("div", class_="push"):
            message    = item.find("span", class_="push-content")
            user_id    = item.find("span", class_="push-userid")
            pro_and_con = item.find("span", class_="push-tag")
            if not (message and user_id and pro_and_con):
                continue
            comment_info.append({
                "User_id":  user_id.text.strip(),
                "Push_tag": pro_and_con.text.strip(),
                "Message":  message.text.strip(),
            })
        for item in main_content.find_all("div", class_="push"):
            item.decompose()
        for item in main_content.find_all("div", class_=lambda c: c and "article" in c):
            item.decompose()
        for item in main_content.find_all("span", class_="f2"):
            item.decompose()
        for line in main_content.text.strip().split("\n"):
            if "引述" in line:
                continue
            if line.startswith(": ") or line.startswith("http"):
                continue
            if line.strip():
                article_content.append(line.strip())
        article_content = "\n".join(article_content)
        time.sleep(0.3)
        return {"Content": article_content, "Comment_info": comment_info}
    return None
